name: Deploy Backend to Server

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # - name: Enable Corepack
      #   run: corepack enable

      # - name: Install Yarn with Corepack
      #   run: corepack prepare yarn@4.5.3 --activate

      - name: Установка зависимостей
        run: |
          yarn install

      - name: Деплой на сервер
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/root/taskera/frontend
            git checkout -- .
            git pull origin master
            yarn install
            yarn build
            pm2 restart frontend || pm2 start yarn --name frontend -- start
